note/note/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('noteapp.urls')),
]

note/noteapp/urls.py
from django.urls import path
from . import views

app_name = 'noteapp'

urlpatterns = [
    path('', views.main, name='main'),
    path('add_tag/', views.add_tag, name='add_tag'),
    path('add_note/', views.add_note, name='add_note'),
    path('detail/<int:note_id>', views.detail, name='detail'),
    path('delete/<int:note_id>', views.delete_note, name='delete'),
    # path('search/', views.search_notes, name='search_notes'),
    path('edit/<int:note_id>/', views.edit_note, name='edit_note'),
    path('search_and_sort/', views.search_and_sort_notes, name='search_and_sort_notes'),

    
    
    
]

note/noteapp/models.py
from django.db import models


# Create your models here.
class Tag(models.Model):
    name = models.CharField(max_length=25, null=False, unique=True)

    def __str__(self):
        return f"{self.name}"


class Note(models.Model):
    name = models.CharField(max_length=50, null=False)
    description = models.CharField(max_length=150, null=False)
    created = models.DateTimeField(auto_now_add=True)
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return f"{self.name}"

note/noteapp/forms.py
from django.forms import ModelForm, CharField, TextInput
from .models import Tag, Note


class TagForm(ModelForm):
    name = CharField(min_length=3, max_length=25, required=True, widget=TextInput())
    class Meta:
        model = Tag
        fields = ['name']
        
class NoteForm(ModelForm):

    name = CharField(min_length=5, max_length=50, required=True, widget=TextInput())
    description = CharField(min_length=10, max_length=150, required=True, widget=TextInput())

    class Meta:
        model = Note
        fields = ['name', 'description']
        exclude = ['tags']

note/noteapp/views.py
from .forms import TagForm, NoteForm
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404
from .models import *

def main(request):
    notes = Note.objects.all()
    return render(request, 'noteapp/index.html', {"notes": notes})

def add_tag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='noteapp:main')
        else:
            return render(request, 'noteapp/add_tag.html', {'form': form})

    return render(request, 'noteapp/add_tag.html', {'form': TagForm()})

def add_note(request):
    tags = Tag.objects.all()

    if request.method == 'POST':
        form = NoteForm(request.POST)
        if form.is_valid():
            new_note = form.save()

            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'))
            for tag in choice_tags.iterator():
                new_note.tags.add(tag)

            return redirect(to='noteapp:main')
        else:
            return render(request, 'noteapp/add_note.html', {"tags": tags, 'form': form})

    return render(request, 'noteapp/add_note.html', {"tags": tags, 'form': NoteForm()})

def detail(request, note_id):
    note = get_object_or_404(Note, pk=note_id)
    return render(request, 'noteapp/detail.html', {"note": note})

def delete_note(request, note_id):
    Note.objects.get(pk=note_id).delete()
    return redirect(to='noteapp:main')

# # Додавання функціоналу пошуку
# def search_notes(request):
#     query = request.GET.get('query', '')
#     notes = Note.objects.filter(name__icontains=query)
#     return render(request, 'notebook/search_results.html', {"notes": notes, "query": query})

def edit_note(request, note_id):
    note = get_object_or_404(Note, pk=note_id)
    all_tags = Tag.objects.all()

    if request.method == 'POST':
        form = NoteForm(request.POST, instance=note)
        if form.is_valid():
            edited_note = form.save(commit=False)
            edited_note.tags.clear()
            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'))
            for tag in choice_tags.iterator():
                edited_note.tags.add(tag)
            edited_note.save()
            return redirect(to='noteapp:main')
        else:
            return render(request, 'noteapp/edit_note.html', {"note": note, 'form': form, 'all_tags': all_tags})
    else:
        form = NoteForm(instance=note)
        return render(request, 'noteapp/edit_note.html', {"note": note, 'form': form, 'all_tags': all_tags})

def search_and_sort_notes(request):
    query = request.GET.get('query', '')
    tag_name = request.GET.get('tag', '')

    notes = Note.objects.filter(name__icontains=query)
    if tag_name:
        notes = notes.filter(tags__name=tag_name)

    all_tags = Tag.objects.all()

    return render(request, 'noteapp/index.html', {"notes": notes, "all_tags": all_tags, "query": query, "tag_name": tag_name})

note/noteapp/templates/noteapp/add_note.html
{% extends "noteapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'noteapp:add_note' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Note name:
            {{ form.name }}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div style="padding: 10px">
        <label> Note description:
            {{ form.description }}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>
    <div style="padding: 10px">
        <label> Select tags:
            <select name="tags" multiple="multiple" required>
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

note/noteapp/templates/noteapp/add_tag.html
{% extends "noteapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'noteapp:add_tag' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the tag name:
            {{form.name}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

note/noteapp/templates/noteapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Note information</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
    {% load static %}
    <link rel="stylesheet" href="{% static 'noteapp/style.css' %}">
</head>
<body>
<main class="container">
    <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
        <ul>
            <li><a href="/" role="button"> Go back to the main page </a></li>
        </ul>
    </nav>
    {% block content %} {% endblock %}
</main>
</body>
</html>

note/noteapp/templates/noteapp/detail.html
{% extends "noteapp/base.html" %} {% load extract_tags %} {% block content %}

<h1>{{note.name}}</h1>
<p>Description: <b>{{note.description}}</b></p>
<p>Time of creation: <kbd>{{note.created}}</kbd></p>
<p>Tags: <small> {{ note.tags|tags }} </small></p>
{% endblock %}

note/noteapp/templates/noteapp/edit_note.html
{% extends "noteapp/base.html" %}

{% block content %}

<h2>Edit Note</h2>

<form method="POST" action="{% url 'noteapp:edit_note' note.id %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Note name:
            {{ form.name }}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div style="padding: 10px">
        <label>Note description:
            {{ form.description }}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>
    <div style="padding: 10px">
        <label>Select tags:
            <select name="tags" multiple="multiple" required>
                {% for tag in all_tags %}
                    <option value="{{ tag.name }}" {% if tag in note.tags.all %}selected{% endif %}>{{ tag.name }}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div class="grid">
        <button type="submit">Save changes</button>
        <a href="{% url 'noteapp:main' %}" role="button" class="secondary">Cancel</a>
    </div>
</form>

{% endblock %}

note/noteapp/templates/noteapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Organizer</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
</head>
<body>
<main class="container">
    <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
        <ul>
            <li><a href="{% url 'noteapp:add_note' %}" role="button">Add note</a></li>
            <li><a href="{% url 'noteapp:add_tag' %}" role="button">Add Tag</a></li>
        </ul>
    </nav>
    {% comment %} <!-- Додавання форми пошуку -->
    <form method="get" action="{% url 'notebook:search_notes' %}">
        <input type="text" name="query" placeholder="Search notes...">
        <button type="submit">Search</button>
    </form> {% endcomment %}
    <!-- Додавання форми пошуку та сортування -->
    <form method="get" action="{% url 'noteapp:search_and_sort_notes' %}">
        <input type="text" name="query" placeholder="Search notes...">
        <select name="tag">
            <option value="" selected>All Tags</option>
            {% for tag in all_tags %}
                <option value="{{ tag.name }}">{{ tag.name }}</option>
            {% endfor %}
        </select>
        <button type="submit">Search</button>
    </form>

    {% for note in notes %}
    <ul>
        <li>
            {% if note %}
            <a href="{% url 'noteapp:detail' note.id %}" role="button" class="outline"> {{ note.name }} </a>
            
            <a href="{% url 'noteapp:delete' note.id %}" role="button" class="contrast"> Delete note </a>
            <!-- Додавання посилання на сторінку редагування -->
            <a href="{% url 'noteapp:edit_note' note.id %}" role="button" class="contrast">Edit note</a>
            {% else %}
            <a href="{% url 'noteapp:detail' note.id %}" role="button" class="secondary"><s>{{ note.name }}</s></a>
            {% endif %}
            
            
        </li>
    </ul>
    {% endfor %}

</main>
</body>
</html>

note/noteapp/templates/noteapp/search_results.html
{% extends "noteapp/base.html" %}

{% block content %}

<h2>Search Results for '{{ query }}'</h2>

{% if notes %}
    <ul>
        {% for note in notes %}
            <li>
                <a href="{% url 'noteapp:detail' note.id %}" role="button" class="outline">{{ note.name }}</a>
                <a href="{% url 'noteapp:delete' note.id %}" role="button" class="contrast">Delete note</a>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No results found.</p>
{% endif %}

{% endblock %}